{
  "hash": "cc30c0550fc0005e6438ae3cd336f8a4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ncode-annotations: hover\ncitation-location: margin\n---\n\n\n\n# Assumptieschendingen oplossen\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Packages\nlibrary(ggResidpanel)   #<1> \nlibrary(rio)            #<2>\nlibrary(tidyverse)      #<3>\nlibrary(modelsummary)   #<4>\nlibrary(marginaleffects) #<5>\nlibrary(broom) #<6>\n\n# Gebruikte datasets\ndemdata <- import(\"demdata.rds\")\ness_demsatis <- import(\"ess_demsatis.dta\")\nnormal_residual_data <- import(\"normal_residual_data.rda\")\nserial_data <- import(\"./data/serial_autocorrelation.rda\")\n```\n:::\n\n\n\n1.  Assumpties testen met plots\n2.  Data importeren\n3.  Datamanipulatie/plots\n4.  Regressietabellen maken\n5.  Voorspelde waarden en marginale effecten\n6.  Gegevens samenvatten\n\n::: {.callout-note title=\"Voor wie is deze Appendix?\"}\nJe hoeft niet te weten hoe je deze analyses moet uitvoeren voor de opdrachten in Statistiek II. Deze gids is bedoeld voor studenten die hun eindpaper schrijven voor Academische Vaardigheden: Kwantitatieve Data-Analyse of een BAP-scriptieproject en graag assumptieschendingen willen vermijden.\n:::\n\nRegressiemodellen zijn gebaseerd op een aantal assumpties of aannames. Een belangrijk onderdeel van de analyse is nagaan of aan die assumpties voldaan is. Zoniet, dan moeten assumptieschendingen op een passende manier behandeld worden. Statistiek II richt zich meer op het eerste deel van het proces: wanneer is niet voldaan aan een assumptie? In deze Appendix geven we een kort overzicht van enkele mogelijke oplossingen voor assumptieschendingen waar je mee geconfronteerd kan worden.\n\n## Assumpties over de fouten (residuals) in OLS modellen\n\n$$\ny_{i} = b_{0} + b_{1} * x_{1} + b_{2} * x_{2} ... b_{k} * x_{k} + e_{i}\n$$\n\nDe $e_{i}$ term in bovenstaande vergelijking staat voor de 'error', fout, of residual in een linear regressiemodel. Er zijn drie assumpties over deze fouten:[^errors-1]\n\n[^errors-1]: Slechts een van deze assumpties is ook van toepassing op logistische modellen: de assumptie van onafhankelijke fouten. De oplossingen hiervoor zijn dezelfde bij logistische modellen, vandaar dat we ons in deze voorbeelden richten op OLS modellen.\n\n-   De variantie van de residuals is *constant* over het hele bereik van de voorspellingen van het model (homoskedasticiteit)\n-   De residuals zijn *onafhankelijk* van elkaar\n-   De residuals volgen een *normaalverdeling* met een gemiddelde van 0\n\nSchendingen van deze assumpties hebben belangrijke gevolgen voor statistische significantietests. Ernstige schendingen leiden tot onbetrouwbare schattingen van de standaardfout van een coëfficiënt en, als gevolg daarvan, tot onjuiste oordelen over statistische significantie.\n\n## Omgaan met Heteroskedasticiteit\n\n### Wat was het probleem ook al weer?\n\nOnderstaand voorbeeld komt uit @sec-ols-assumptions en voorspelt de mate van politieke stabiliteit in een land op basis van democratieniveaus. In het voorbeeld hebben we ook een kwadratische term voor democratiescore toegevoegd om non-lineaire verbanden te kunnen vatten. Hier is het model en de resultaten:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#gekwadrateerde variabele maken\ndemdata <- demdata |> \n  mutate(v2x_polyarchy_sq = v2x_polyarchy^2)\n\n# Model schatten\nviolence_sqmodel <- lm(pve ~ v2x_polyarchy + v2x_polyarchy_sq, \n                      data=demdata)\n\n# coëfficiënten bekijken\ntidy(violence_sqmodel, conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 7\n  term             estimate std.error statistic  p.value conf.low conf.high\n  <chr>               <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>\n1 (Intercept)        -0.589     0.243     -2.42 0.0165      -1.07    -0.109\n2 v2x_polyarchy      -1.73      1.10      -1.58 0.117       -3.90     0.438\n3 v2x_polyarchy_sq    3.83      1.05       3.64 0.000361     1.75     5.90 \n```\n\n\n:::\n:::\n\n\n\nWe kunnen kijken of de assumptie van homoskedasticiteit geschonden is via `resid_panel()` zoals besproken in @sec-ols-assumptions.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# assumptie bekijken\nresid_panel(violence_sqmodel, plots = c(\"resid\"))\n```\n\n::: {.cell-output-display}\n![](errors_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\nAan de assumptie is voldaan als de fouten een even grote spreiding kennen op lage, gemiddelde, en hoge waarden van de voorspelde waarden. Ze moeten zich ongeveer in een evenwijdige band bevinden. Hier zien we dat de assumptie geschonden is aan de trechtervorm: we vinden een grote spreiding van residuals bij lage voorspele waarden (de schatting is hier onnauwkeurig) en weinig spreiding bij hoge voorspelde waarden (de schatting is hier veel nauwkeuriger).\n\n### Mogelijke oplossing: robuste standaardfouten\n\n::: callout-note\nDe `vcov` functie die we hieronder gebruiken is afkomstig uit het`sandwich`package en helpt bij de berekening van robuuste standaardfouten. Je zult dit package misschien eerst moeten installeren.\n:::\n\nHeteroskedasticiteit heeft verschillende mogelijke oorzaken. Zo kan het onstaan door het ontbrekenen van belangrijke predictoren in het model. Het is een goed idee om na te denken over waarom de residuals zo verschillen en welke bijkomende onafhankelijke variabele deze spreiding kan verklaren. We kunnen dit echter niet altijd weten en als we al een idee hebben, kan het zijn dat de relevante onafhankelijke variabele niet in de dataset voorkomt.\n\nEen andere mogelijke oorzaak is dat we een lineaire relatie schatten waar eigenlijk een niet-lineaire relatie geschat moet worden. Dit is hier echter niet het geval.\n\nWat kunnen we dan nog doen?\n\nEen gangbare manier is om de berekenmethode voor de standaardfouten van de coëfficiënten in het model aan te passen. De standaardfouten die normaal door R worden berekend gaan uit van homoskedasticiteit, maar we kunnen 'heteroskedasticiteit-robuuste' standaardfouten berekenen als alternatief. Belangrijk is om te onthouden dat deze oplossing een mathematisch 'truukje' is, ons model past nog altijd slecht en het is belangrijk theoretisch hierover na te denken. De eerste stap blijft altijd om na te denken over mogelijk ontbrekende predictoren.\n\nDe eenvoudigste manier om robuuste standaardfouten te verkrijgen is via het `modelsummary` package. We bekijken eerst nog even de 'normale' regressie-output voor het model:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelsummary(violence_sqmodel, \n             stars = T, \n             coef_rename = c(\n               \"(Intercept)\" = \"Intercept\", \n               \"v2x_polyarchy\" = \"Democratiescore\", \n               \"v2x_polyarchy_sq\" = \"Democratiescore gekwadrateerd\"), \n             gof_map = c(\"nobs\", \"r.squared\", \"adj.r.squared\"))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_ry5w6adrjmyyl6zzcab1(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_ry5w6adrjmyyl6zzcab1\");\n          var cell = table.rows[i]?.cells[j];  // Safe navigation to avoid errors\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function insertSpanRow(i, colspan, content) {\n        var table = document.getElementById('tinytable_ry5w6adrjmyyl6zzcab1');\n        var newRow = table.insertRow(i);\n        var newCell = newRow.insertCell(0);\n        newCell.setAttribute(\"colspan\", colspan);\n        // newCell.innerText = content;\n        // this may be unsafe, but innerText does not interpret <br>\n        newCell.innerHTML = content;\n      }\n      function spanCell_ry5w6adrjmyyl6zzcab1(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_ry5w6adrjmyyl6zzcab1\");\n        const targetRow = table.rows[i];\n        const targetCell = targetRow.cells[j];\n        for (let r = 0; r < rowspan; r++) {\n          // Only start deleting cells to the right for the first row (r == 0)\n          if (r === 0) {\n            // Delete cells to the right of the target cell in the first row\n            for (let c = colspan - 1; c > 0; c--) {\n              if (table.rows[i + r].cells[j + c]) {\n                table.rows[i + r].deleteCell(j + c);\n              }\n            }\n          }\n          // For rows below the first, delete starting from the target column\n          if (r > 0) {\n            for (let c = colspan - 1; c >= 0; c--) {\n              if (table.rows[i + r] && table.rows[i + r].cells[j]) {\n                table.rows[i + r].deleteCell(j);\n              }\n            }\n          }\n        }\n        // Set rowspan and colspan of the target cell\n        targetCell.rowSpan = rowspan;\n        targetCell.colSpan = colspan;\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: 0, j: 0 },  ], css_id: 'tinytable_css_yuv9v6mn4bleg9152keo',}, \n          { positions: [ { i: 6, j: 0 },  ], css_id: 'tinytable_css_sux6v2ymrl97x0n6ipk5',}, \n          { positions: [ { i: 9, j: 1 },  ], css_id: 'tinytable_css_suwba0ui7li5v5zszklg',}, \n          { positions: [ { i: 0, j: 1 },  ], css_id: 'tinytable_css_koipfppa4bqmpm5fv67c',}, \n          { positions: [ { i: 1, j: 0 }, { i: 2, j: 0 }, { i: 3, j: 0 }, { i: 4, j: 0 }, { i: 5, j: 0 }, { i: 7, j: 0 }, { i: 8, j: 0 },  ], css_id: 'tinytable_css_gztp0o5m83k316fzpczl',}, \n          { positions: [ { i: 6, j: 1 },  ], css_id: 'tinytable_css_7svrbnav1g09x9dn306t',}, \n          { positions: [ { i: 1, j: 1 }, { i: 2, j: 1 }, { i: 3, j: 1 }, { i: 4, j: 1 }, { i: 5, j: 1 }, { i: 7, j: 1 }, { i: 8, j: 1 },  ], css_id: 'tinytable_css_4fj75yyqwk8zb1nghj05',}, \n          { positions: [ { i: 9, j: 0 },  ], css_id: 'tinytable_css_48ezcy0cm6sykh6jzp3l',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_ry5w6adrjmyyl6zzcab1(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_yuv9v6mn4bleg9152keo, .table th.tinytable_css_yuv9v6mn4bleg9152keo { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_sux6v2ymrl97x0n6ipk5, .table th.tinytable_css_sux6v2ymrl97x0n6ipk5 { text-align: left; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_suwba0ui7li5v5zszklg, .table th.tinytable_css_suwba0ui7li5v5zszklg { text-align: center; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_koipfppa4bqmpm5fv67c, .table th.tinytable_css_koipfppa4bqmpm5fv67c { text-align: center; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_gztp0o5m83k316fzpczl, .table th.tinytable_css_gztp0o5m83k316fzpczl { text-align: left; }\n      .table td.tinytable_css_7svrbnav1g09x9dn306t, .table th.tinytable_css_7svrbnav1g09x9dn306t { text-align: center; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_4fj75yyqwk8zb1nghj05, .table th.tinytable_css_4fj75yyqwk8zb1nghj05 { text-align: center; }\n      .table td.tinytable_css_48ezcy0cm6sykh6jzp3l, .table th.tinytable_css_48ezcy0cm6sykh6jzp3l { text-align: left; border-bottom: solid #d3d8dc 0.1em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_ry5w6adrjmyyl6zzcab1\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\"> </th>\n                <th scope=\"col\">(1)</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='2'>+ p < 0.1, * p < 0.05, ** p < 0.01, *** p < 0.001</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td>Intercept</td>\n                  <td>-0.589*</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.243)</td>\n                </tr>\n                <tr>\n                  <td>Democratiescore</td>\n                  <td>-1.731</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(1.098)</td>\n                </tr>\n                <tr>\n                  <td>Democratiescore gekwadrateerd</td>\n                  <td>3.829***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(1.051)</td>\n                </tr>\n                <tr>\n                  <td>Num.Obs.</td>\n                  <td>164</td>\n                </tr>\n                <tr>\n                  <td>R2</td>\n                  <td>0.401</td>\n                </tr>\n                <tr>\n                  <td>R2 Adj.</td>\n                  <td>0.394</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\nDe tabel hierboven maakt gebruik van de normale standaardfouten. We kunnen de robuuste opvragen via de `vcov` optie:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelsummary(violence_sqmodel, \n             stars = T, \n             vcov = \"HC3\",\n             coef_rename = c(\n               \"(Intercept)\" = \"Intercept\", \n               \"v2x_polyarchy\" = \"Democratiescore\", \n               \"v2x_polyarchy_sq\" = \"Democratiescore gekwadrateerd\"), \n             gof_map = c(\"nobs\", \"r.squared\", \"adj.r.squared\"))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_pg788nuwwbyybrgvv54u(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_pg788nuwwbyybrgvv54u\");\n          var cell = table.rows[i]?.cells[j];  // Safe navigation to avoid errors\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function insertSpanRow(i, colspan, content) {\n        var table = document.getElementById('tinytable_pg788nuwwbyybrgvv54u');\n        var newRow = table.insertRow(i);\n        var newCell = newRow.insertCell(0);\n        newCell.setAttribute(\"colspan\", colspan);\n        // newCell.innerText = content;\n        // this may be unsafe, but innerText does not interpret <br>\n        newCell.innerHTML = content;\n      }\n      function spanCell_pg788nuwwbyybrgvv54u(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_pg788nuwwbyybrgvv54u\");\n        const targetRow = table.rows[i];\n        const targetCell = targetRow.cells[j];\n        for (let r = 0; r < rowspan; r++) {\n          // Only start deleting cells to the right for the first row (r == 0)\n          if (r === 0) {\n            // Delete cells to the right of the target cell in the first row\n            for (let c = colspan - 1; c > 0; c--) {\n              if (table.rows[i + r].cells[j + c]) {\n                table.rows[i + r].deleteCell(j + c);\n              }\n            }\n          }\n          // For rows below the first, delete starting from the target column\n          if (r > 0) {\n            for (let c = colspan - 1; c >= 0; c--) {\n              if (table.rows[i + r] && table.rows[i + r].cells[j]) {\n                table.rows[i + r].deleteCell(j);\n              }\n            }\n          }\n        }\n        // Set rowspan and colspan of the target cell\n        targetCell.rowSpan = rowspan;\n        targetCell.colSpan = colspan;\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: 1, j: 0 }, { i: 2, j: 0 }, { i: 3, j: 0 }, { i: 4, j: 0 }, { i: 5, j: 0 }, { i: 7, j: 0 }, { i: 8, j: 0 },  ], css_id: 'tinytable_css_rm7xzuf1qp64sytgu98q',}, \n          { positions: [ { i: 0, j: 0 },  ], css_id: 'tinytable_css_r07imrer4z2att5cxq5l',}, \n          { positions: [ { i: 0, j: 1 },  ], css_id: 'tinytable_css_q8jko9ncgnypz0wza481',}, \n          { positions: [ { i: 9, j: 0 },  ], css_id: 'tinytable_css_pv5jnpdanyj3fvs0a29c',}, \n          { positions: [ { i: 6, j: 1 },  ], css_id: 'tinytable_css_n2zdvm6pwrfg073vi2c0',}, \n          { positions: [ { i: 6, j: 0 },  ], css_id: 'tinytable_css_9ge92a2xmbgzaudf89d6',}, \n          { positions: [ { i: 1, j: 1 }, { i: 2, j: 1 }, { i: 3, j: 1 }, { i: 4, j: 1 }, { i: 5, j: 1 }, { i: 7, j: 1 }, { i: 8, j: 1 },  ], css_id: 'tinytable_css_40ozg0agwd1746x1kx6v',}, \n          { positions: [ { i: 9, j: 1 },  ], css_id: 'tinytable_css_1ns5np782jao05cswr4t',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_pg788nuwwbyybrgvv54u(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_rm7xzuf1qp64sytgu98q, .table th.tinytable_css_rm7xzuf1qp64sytgu98q { text-align: left; }\n      .table td.tinytable_css_r07imrer4z2att5cxq5l, .table th.tinytable_css_r07imrer4z2att5cxq5l { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_q8jko9ncgnypz0wza481, .table th.tinytable_css_q8jko9ncgnypz0wza481 { text-align: center; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_pv5jnpdanyj3fvs0a29c, .table th.tinytable_css_pv5jnpdanyj3fvs0a29c { text-align: left; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_n2zdvm6pwrfg073vi2c0, .table th.tinytable_css_n2zdvm6pwrfg073vi2c0 { text-align: center; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_9ge92a2xmbgzaudf89d6, .table th.tinytable_css_9ge92a2xmbgzaudf89d6 { text-align: left; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_40ozg0agwd1746x1kx6v, .table th.tinytable_css_40ozg0agwd1746x1kx6v { text-align: center; }\n      .table td.tinytable_css_1ns5np782jao05cswr4t, .table th.tinytable_css_1ns5np782jao05cswr4t { text-align: center; border-bottom: solid #d3d8dc 0.1em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_pg788nuwwbyybrgvv54u\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\"> </th>\n                <th scope=\"col\">(1)</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='2'>+ p < 0.1, * p < 0.05, ** p < 0.01, *** p < 0.001</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td>Intercept</td>\n                  <td>-0.589+</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.303)</td>\n                </tr>\n                <tr>\n                  <td>Democratiescore</td>\n                  <td>-1.731</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(1.249)</td>\n                </tr>\n                <tr>\n                  <td>Democratiescore gekwadrateerd</td>\n                  <td>3.829***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(1.107)</td>\n                </tr>\n                <tr>\n                  <td>Num.Obs.</td>\n                  <td>164</td>\n                </tr>\n                <tr>\n                  <td>R2</td>\n                  <td>0.401</td>\n                </tr>\n                <tr>\n                  <td>R2 Adj.</td>\n                  <td>0.394</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\n`vcov = \"HC3\"`\n\n:   De `vcov =` optie vraagt om robuuste standaardfouten te berekenen en te gebruiken in de tabel. \"HC3\" staat voor 'heteroskedasticiteit-robuuste standardfouten'. Er zijn verschillende heteroskedasticiteit-robuuste standaardfouten (bv., \"HC0\", \"HC1\", etc.). We raden \"HC3\" aan als standaard, ook omdat deze goed werkt bij kleine steekproefgroottes.\n\nLaten we de 'normale' en 'robuuste' standaardfouten vergelijken:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelsummary(violence_sqmodel, \n             stars = T, \n             vcov = c(\"classical\", \"HC3\"), \n             coef_rename = c(\n               \"(Intercept)\" = \"Intercept\", \n               \"v2x_polyarchy\" = \"Democratiescore\", \n               \"v2x_polyarchy_sq\" = \"Democratiescore gekwadrateerd\"),\n             gof_map = c(\"nobs\", \"r.squared\", \"adj.r.squared\"))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_7yhqrk614ax444e0myil(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_7yhqrk614ax444e0myil\");\n          var cell = table.rows[i]?.cells[j];  // Safe navigation to avoid errors\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function insertSpanRow(i, colspan, content) {\n        var table = document.getElementById('tinytable_7yhqrk614ax444e0myil');\n        var newRow = table.insertRow(i);\n        var newCell = newRow.insertCell(0);\n        newCell.setAttribute(\"colspan\", colspan);\n        // newCell.innerText = content;\n        // this may be unsafe, but innerText does not interpret <br>\n        newCell.innerHTML = content;\n      }\n      function spanCell_7yhqrk614ax444e0myil(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_7yhqrk614ax444e0myil\");\n        const targetRow = table.rows[i];\n        const targetCell = targetRow.cells[j];\n        for (let r = 0; r < rowspan; r++) {\n          // Only start deleting cells to the right for the first row (r == 0)\n          if (r === 0) {\n            // Delete cells to the right of the target cell in the first row\n            for (let c = colspan - 1; c > 0; c--) {\n              if (table.rows[i + r].cells[j + c]) {\n                table.rows[i + r].deleteCell(j + c);\n              }\n            }\n          }\n          // For rows below the first, delete starting from the target column\n          if (r > 0) {\n            for (let c = colspan - 1; c >= 0; c--) {\n              if (table.rows[i + r] && table.rows[i + r].cells[j]) {\n                table.rows[i + r].deleteCell(j);\n              }\n            }\n          }\n        }\n        // Set rowspan and colspan of the target cell\n        targetCell.rowSpan = rowspan;\n        targetCell.colSpan = colspan;\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: 6, j: 2 }, { i: 6, j: 1 },  ], css_id: 'tinytable_css_rsljvq4b6fj9pf8tibo7',}, \n          { positions: [ { i: 9, j: 0 },  ], css_id: 'tinytable_css_ls9ded9osm1t6itb688b',}, \n          { positions: [ { i: 9, j: 1 }, { i: 9, j: 2 },  ], css_id: 'tinytable_css_itxcrup80fleglrxstkz',}, \n          { positions: [ { i: 1, j: 0 }, { i: 2, j: 0 }, { i: 3, j: 0 }, { i: 4, j: 0 }, { i: 5, j: 0 }, { i: 7, j: 0 }, { i: 8, j: 0 },  ], css_id: 'tinytable_css_dlganm48yg2rn4nrw7ip',}, \n          { positions: [ { i: 0, j: 1 }, { i: 0, j: 2 },  ], css_id: 'tinytable_css_bb2psylpb69vd4tirxil',}, \n          { positions: [ { i: 6, j: 0 },  ], css_id: 'tinytable_css_68abq2pai9lovvr1eonp',}, \n          { positions: [ { i: 0, j: 0 },  ], css_id: 'tinytable_css_67364k1dzcbcjseubvfm',}, \n          { positions: [ { i: 1, j: 1 }, { i: 3, j: 1 }, { i: 4, j: 1 }, { i: 5, j: 1 }, { i: 2, j: 1 }, { i: 7, j: 1 }, { i: 8, j: 1 }, { i: 3, j: 2 }, { i: 4, j: 2 }, { i: 1, j: 2 }, { i: 2, j: 2 }, { i: 7, j: 2 }, { i: 8, j: 2 }, { i: 5, j: 2 },  ], css_id: 'tinytable_css_3u85r28q7tv0nmed3vj3',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_7yhqrk614ax444e0myil(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_rsljvq4b6fj9pf8tibo7, .table th.tinytable_css_rsljvq4b6fj9pf8tibo7 { text-align: center; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_ls9ded9osm1t6itb688b, .table th.tinytable_css_ls9ded9osm1t6itb688b { text-align: left; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_itxcrup80fleglrxstkz, .table th.tinytable_css_itxcrup80fleglrxstkz { text-align: center; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_dlganm48yg2rn4nrw7ip, .table th.tinytable_css_dlganm48yg2rn4nrw7ip { text-align: left; }\n      .table td.tinytable_css_bb2psylpb69vd4tirxil, .table th.tinytable_css_bb2psylpb69vd4tirxil { text-align: center; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_68abq2pai9lovvr1eonp, .table th.tinytable_css_68abq2pai9lovvr1eonp { text-align: left; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_67364k1dzcbcjseubvfm, .table th.tinytable_css_67364k1dzcbcjseubvfm { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_3u85r28q7tv0nmed3vj3, .table th.tinytable_css_3u85r28q7tv0nmed3vj3 { text-align: center; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_7yhqrk614ax444e0myil\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\"> </th>\n                <th scope=\"col\">(1)</th>\n                <th scope=\"col\">(2)</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='3'>+ p < 0.1, * p < 0.05, ** p < 0.01, *** p < 0.001</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td>Intercept</td>\n                  <td>-0.589*</td>\n                  <td>-0.589+</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.243)</td>\n                  <td>(0.303)</td>\n                </tr>\n                <tr>\n                  <td>Democratiescore</td>\n                  <td>-1.731</td>\n                  <td>-1.731</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(1.098)</td>\n                  <td>(1.249)</td>\n                </tr>\n                <tr>\n                  <td>Democratiescore gekwadrateerd</td>\n                  <td>3.829***</td>\n                  <td>3.829***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(1.051)</td>\n                  <td>(1.107)</td>\n                </tr>\n                <tr>\n                  <td>Num.Obs.</td>\n                  <td>164</td>\n                  <td>164</td>\n                </tr>\n                <tr>\n                  <td>R2</td>\n                  <td>0.401</td>\n                  <td>0.401</td>\n                </tr>\n                <tr>\n                  <td>R2 Adj.</td>\n                  <td>0.394</td>\n                  <td>0.394</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\nDe eerste kolom toont de resultaten voor de 'normale' standaardfouten, de tweede kolom deze voor de 'robuuste' fouten. We kunnen het volgende opmerken:\n\n-   De coëfficiënten veranderen niet, enkel de standaardfouten.\n-   De robuuste standaardfouten zijn typisch groter. Heteroskedasticiteit zorgt immers doorgaans voor een neerwaarste bias: standaarfouten worden te klein geschat als we de normale methode zouden gebruiken.\n-   De interpretatie van de resultaten verandert hier niet. De significantietoetsen voor de predictoren komen uit op dezelfde conclusies. Di is echter lang niet altijd het geval!\n\nHet voorbeeld hierboven maakt gebruik van `modelsummary()` en geeft de resultaten weer in een tabel. Ook voor voorspelde waarden en coëfficiëntenplots kunnen we robuuste standaardfouten gebruiken zodanig dat betrouwbaarheidsintervallen aangepast worden.\n\nWe blijven de bovenstaande `vcov` optie gebruiken, maar binnen de `predictions()` functie uit het `marginaleffects` package (bv., `predictions(model, ..., vcov = \"HC3\")`) voor voorspelde waarden.\n\nVoor coëfficiëntenplots kunnen we de syntax echter niet netjes combineren met `tidy()` zoals we deden in @sec-reporting-and-presenting-results. In de plaats daarvan gebruiken we de `avg_slopes()` functie uit het `marginaleffects` package. `avg_slopes()` schat de marginale effecten van elke predictor in het model. Bij OLS is dit gelijk aan de coëfficiënten.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Resultaten via tidy\ntidy(violence_sqmodel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term             estimate std.error statistic  p.value\n  <chr>               <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)        -0.589     0.243     -2.42 0.0165  \n2 v2x_polyarchy      -1.73      1.10      -1.58 0.117   \n3 v2x_polyarchy_sq    3.83      1.05       3.64 0.000361\n```\n\n\n:::\n\n```{.r .cell-code}\n# Resultaten  via avg_slopes\navg_slopes(violence_sqmodel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n             Term Estimate Std. Error     z Pr(>|z|)    S 2.5 % 97.5 %\n v2x_polyarchy       -1.73       1.10 -1.58    0.115  3.1 -3.88  0.421\n v2x_polyarchy_sq     3.83       1.05  3.64   <0.001 11.9  1.77  5.888\n\nType:  response \nComparison: dY/dX\n```\n\n\n:::\n:::\n\n\n\nWe voegen de `vcov =` optie toe aan de `avg_slopes()` functie en plotten de resultaten:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# robuuste SEs en plot\navg_slopes(violence_sqmodel, vcov = \"HC3\") |> # <1>\n  ggplot(aes(x = estimate, y = term)) + \n  geom_pointrange(aes(xmin = conf.low, xmax = conf.high)) + \n  geom_text(aes(label = round(estimate, 2)), vjust = -0.5) + \n  geom_vline(xintercept = 0, linetype = 'dashed', color = 'red') + \n  theme_bw() + \n  labs(x = \"Coëfficiënt\", \n       y = \"Onafhankelijke variabele\", \n       title = \"Coëfficiënten met Heteroskedasticiteit-robuuste betrouwbaarheidsintervallen\")\n```\n\n::: {.cell-output-display}\n![](errors_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\n1.  Opvragen van marginale effecten van de predictoren samen met de robuuste standaardfouten.\n\n## Omgaan met afhankelijke fouten\n\nEen tweede belangrijke assumptie in OLS (en logistische) modellen is deze van *onafhankelijkheid*. We gaan ervan uit dat de fouten in de populatie en in ons model niet gecorreleerd zijn met elkaar. Deze assumptie kan geschonden zijn wanneer data 'geclusterd' is.\n\n### Probleem 1: geclusterde data\n\n#### Voorbeeld van het probleem\n\nStel dat we meten in welke mate burgers tevreden zijn met democratie in verschillende Europese landen (bv. met links-rechtspositie als predictor). We kunnen de European Social Survey (ESS) gebruike, waarbij respondenten uit verschillende landen werden ondervraagd. Wanneer de analyse meerdere landen beschouwt, zijn respondenten geclustert in hun land.\n\nWe bekijken de resultaten van een dergelijk model. De afhankelijke variabele meet tevredenheid met democratie op een schaal van 0 (\"zeer ontevreden\") tot 10 (\"zeer tevreden\"). De onafhankelijke variabele meet links-rechtspositie met een schaal van 0 (\"links\") tot 10 (\"rechts\").\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model \ndemsatis_model <- lm(stfdem ~ lrscale, data = ess_demsatis)\n\n# Coefficients\ntidy(demsatis_model, conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 7\n  term        estimate std.error statistic   p.value conf.low conf.high\n  <chr>          <dbl>     <dbl>     <dbl>     <dbl>    <dbl>     <dbl>\n1 (Intercept)    4.53    0.0308      147.  0            4.47      4.59 \n2 lrscale        0.128   0.00556      23.1 7.97e-117    0.117     0.139\n```\n\n\n:::\n:::\n\n\n\nDe coëfficiënt voor links-rechtspositie (`lrscale`) is positief: mensen die zich meer aan de rechterkant van het politieke spectrum plaatsen zijn meer tevreden met democratie. De coëfficiënt is ook statistisch significant met wel een heel kleine p-waarde (7.97e-117). Laten we echter kijken hoe clustering hier bij komt kijken.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\n# Extra package for plotting\nlibrary(patchwork) # <1>\n\n# Distribution plot\ndistribution_plot <- ess_demsatis |> \n  group_by(country_name, stfdem) |> # <2>\n  tally() |> \n  ungroup() |> \n  group_by(country_name) |> # <3>\n  mutate(prop = n / sum(n)) |>\n  ggplot(aes(x = stfdem, y = prop)) + \n  geom_col() +\n  facet_wrap(~ country_name) + \n  theme_bw() + \n  labs(title = \"Variatie volgens Land\", \n       y = \"Proportie\", \n       x = \"Tevredenheidsscore\") + \n  scale_x_continuous(breaks = c(0,5,10))\n\n# Plot of means\nmean_plot <- ess_demsatis |> \n  group_by(country_name) |> \n  summarize(dem_satis = mean(stfdem, na.rm = T)) |> \n  ggplot(aes(x = dem_satis, y = reorder(country_name, dem_satis))) + # <4>\n  geom_col() + \n  theme_bw() + \n  labs(title = \"Gemiddelde per land\", \n       y = \"Naam land\", \n       x = \"Gemiddelde tevredenheid met democratie\")\n\n# Combine together using patchwork\ndistribution_plot + mean_plot\n```\n\n::: {.cell-output-display}\n![](errors_files/figure-html/unnamed-chunk-11-1.png){width=1152}\n:::\n:::\n\n\n\n1.  De `patchwork` library wordt hier gebruikt om meerdere grafieken te combineren met elkaar.\n2.  Deze regels berekenen het aantal antwoorden per antwoordcategorie per land.\n3.  We berekenen hier de proportie van observaties met een specifieke respons per land.\n4.  De `reorder()` optie herordent de y-as zodat die loopt van hogere tot lagere gemiddelde scores.\n\nHet linkse plot in de figuur hierboven toont de proportie observaties per antwoordcategorie (x-as) per land (aparte 'facets'). De plot toont variatie tussen individuen binnen een land: sommige zijn tevreden, andere niet. De verdeling van observaties is echter niet dezelfde per land. Sommige landen zien meer tevreden respondenten (bv., Finland, Norwegen, en Zwitserland) terwijl in andere landen mensen zich meer onderaan de schaal bevinden (bv., Bulgarije, Servië, en Griekenland).\n\nEr is dus niet alleen variatie tussen individuen, maar ook variatie *tussen landen*. Dit zien we ook op het rechtse plot, dat de gemiddelde tevedenheidsscore per land weergeeft.[^errors-2]\n\n[^errors-2]: Wel zien we dat er meer variatie is tussen individuen dan tussen landen. dat is wel vaker zo in dergelijke cross-nationale surveydatasets.\n\nDemocratische tevredenheid is hoger in sommige landen dan andere. Daar kunnen verschillende redenen voor bestaan: andere politieke instituties, economische welvaart, corruptieniveaus enz. Mensen binnen een land leven in een context waarin die factoren gelijk zijn, maar mensen buiten een bepaald land leven in andere omstandigheden. We kunne dan ook verwachten dat errors van mensen binnen een bepaald land gecorreleerd zijn met elkaar in een studie waarbij meerdere landen zijn opgenomen.De standaardfouten in het model zijn dan wellicht ook niet correct.[^errors-3]\n\n[^errors-3]: We moeten er ook op letten dat er geen 'ommitted variable bias' optreedt. Hier gebruiken we bijvoorbeeld slechts 1 predictor en belangrijke controlevariabelen worden wellicht over het hoofd gezien.\n\nWe kunnen 2 methoden gebruiken om dit te corrigeren:[^errors-4]\n\n[^errors-4]: Er bestaan eigenlijk ook twee andere strategieën. Het probleem hier wordt veroorzaakt door het samenbrengen (\"poolen\") van gegevens uit verschillende landen (\"clusters\"). Het kan echter zijn dat we ons zorgen maken over één cluster in het bijzonder, bijvoorbeeld het doel van ons artikel kan zijn om de relatie tussen ideologie en democratische tevredenheid specifiek in Duitsland of in Nederland te onderzoeken, enz. Een \"oplossing\" is dan om waarnemingen uit de andere landen weg te filteren en enkel een model voor 1 land te schatten. Het kan ook zijn dat we niet echt geïnteresseerd zijn in het lagere niveau van de dataset (bijv. de individuen in dit voorbeeld) en eigenlijk meer geven om het verklaren van de variatie tussen clusters (bijv. waarom landen als Zwitserland een hogere democratische tevredenheid hebben dan landen als Bulgarije). Een optie hier is om het clustergemiddelde te gebruiken als onze afhankelijke variabele in een regressiemodel en dit te voorspellen met predictoren op landniveau (bv. BBP). Zoals altijd is de eerste stap in elke data-analyse uitzoeken *wat onze vraag is*, omdat dit een grote invloed heeft op het type analyse dat geschikt is om te leren wat we willen leren.\n\nWe kunnen gebruik maken van \"geclusterde standaardfouten\" en \"fixed effects\". Net zoals bij heteroskedasticiteit herberekenen we de standaardfouten (Let op: de berekening is wel anders). Deze corrigeren voor het feit dat de errors van observaties binnen een cluster (hier: land) gecorreleerd zijn. Fixed effects toevoegen houdt in dat we een dummy-variabele toevoegen per cluster (hier:land) om te controleren op variaties in de afhankelijke variabele afkomstig uit kenmerken van de cluster.\n\nSommige onderzoekers maken ook gebruik van \"multilevel modellen\". Met deze modellen kunnen predictoren op het niveau van individuele respondenten alsook predictoren op het cluster-niveau worden toegevoegd (bv. BBP) Deze methode is te gevorderd voor dit handboek en wordt verder niet besproken.\n\n### Mogelijke oplossing: Clustered standard errors & fixed effects\n\nWe schatten ons model met geclusterde standaardfouten met de code uitgelegd hieronder. Om \"fixed effects\" toe te voegen transformeren we gewoon de clustervariabele in een factor-variabele. Wanneer we deze factor toevoegen aan het model neemt R dummies op voor elke cluster, behoudens de referentiecategorie. [^errors-5]\n\n[^errors-5]: Deze strategie werkt ongeacht de hoeveelheid clusters die je hebt. De berekening kan wel langer duren bij een groter aantal clsuters. Stel dat we met longitudinale, panel-data werken van 500 respondenten die elke maand van het jaar bevraagd worden. Voor een 'fixed effects'analyse betekent dit dat je 499 dummies toevoegd. Dit is best veel. In dit geval kun je ook specifieke packages gebruiken die speciaal ontworpen ziin voor 'fixed effects' en vlugger werken, bijvoorbeeld het [fixest](https://lrberge.github.io/fixest/) package met bijhorende `feols` functie. Deze functie gebruikt ook automatisch geclusterde standaardfouten.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# factor maken\ness_demsatis <- ess_demsatis |> \n  mutate(\n    country_name_F = factor(country_name))\n\n# Controleren of alles juist is gegaan: Austria is hier de referentiecategorie\nlevels(ess_demsatis$country_name_F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"Austria\"        \"Belgium\"        \"Bulgaria\"       \"Croatia\"       \n [5] \"Cyprus\"         \"Finland\"        \"France\"         \"Germany\"       \n [9] \"Greece\"         \"Hungary\"        \"Iceland\"        \"Ireland\"       \n[13] \"Israel\"         \"Italy\"          \"Latvia\"         \"Lithuania\"     \n[17] \"Montenegro\"     \"Netherlands\"    \"Norway\"         \"Poland\"        \n[21] \"Portugal\"       \"Serbia\"         \"Slovakia\"       \"Slovenia\"      \n[25] \"Spain\"          \"Sweden\"         \"Switzerland\"    \"United Kingdom\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# Factor toevoegen aan model\ndemsatis_model2 <- lm(stfdem ~ lrscale + country_name_F, data = ess_demsatis)\n\n# Coëfficiënten opvragen\ntidy(demsatis_model2, conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 29 × 7\n   term                estimate std.error statistic   p.value conf.low conf.high\n   <chr>                  <dbl>     <dbl>     <dbl>     <dbl>    <dbl>     <dbl>\n 1 (Intercept)           5.15     0.0568     90.7   0            5.03     5.26  \n 2 lrscale               0.136    0.00521    26.2   4.59e-150    0.126    0.147 \n 3 country_name_FBelg…  -0.550    0.0790     -6.96  3.45e- 12   -0.704   -0.395 \n 4 country_name_FBulg…  -2.42     0.0751    -32.1   7.25e-224   -2.56    -2.27  \n 5 country_name_FCroa…  -1.35     0.0819    -16.5   8.89e- 61   -1.51    -1.19  \n 6 country_name_FCypr…  -1.27     0.108     -11.7   8.62e- 32   -1.49    -1.06  \n 7 country_name_FFinl…   0.885    0.0791     11.2   4.70e- 29    0.730    1.04  \n 8 country_name_FFran…  -1.53     0.0782    -19.6   4.41e- 85   -1.68    -1.38  \n 9 country_name_FGerm…  -0.0598   0.0705     -0.848 3.96e-  1   -0.198    0.0784\n10 country_name_FGree…  -1.62     0.0703    -23.0   1.57e-116   -1.76    -1.48  \n# ℹ 19 more rows\n```\n\n\n:::\n:::\n\n\n\nHet model bevat nu een coëfficiënt voor links-rechtspositie (`lrscale`) en een reeks dummy-variabelen voor elk land (`country_name_FBelgium`, `country_name_FBulgaria`, etc.). Schrik niet van deze output, dit is effectief de bedoeling!\n\nDe coëfficient voor `lrscale` toont de associatie tussen links-rechtspositie en tevredenheid met democratie, gecontroleerd voor het land waar de respondent zich bevindt. De dummy-coëfficiënten tonen het verschil tussen elk land en de referentiecategorie (Oostenrijk), gecontroleerd voor `lrscale`. We vinden bijvoorbeeld dat als we Bulgaarse en Oostenrijkse burgers met dezelfde ideologiescore zouden vergelijken, dan zouden we verwachten dat tevredenheid van Bulgaarse burgers gemiddeld genomen 2.42 eenheden lager is dan die van Oostenrijkse burgers.\n\nDe resultaten hieboven maken nog gebruik van de 'normale' standaardfouten. We kunnen de geclusterde standaardfouten toevoegen via `modelsummary()` met de `vcov =` optie, zoals hieronder (`coef_rename` hebben we hier even weggelaten).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelsummary(\n  demsatis_model2, \n  stars = T, \n  vcov = ~country_name_F, \n  gof_map = c(\"nobs\", \"r.squared\", \"adj.r.squared\"))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_xx1zgyz6jocp066tk7px(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_xx1zgyz6jocp066tk7px\");\n          var cell = table.rows[i]?.cells[j];  // Safe navigation to avoid errors\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function insertSpanRow(i, colspan, content) {\n        var table = document.getElementById('tinytable_xx1zgyz6jocp066tk7px');\n        var newRow = table.insertRow(i);\n        var newCell = newRow.insertCell(0);\n        newCell.setAttribute(\"colspan\", colspan);\n        // newCell.innerText = content;\n        // this may be unsafe, but innerText does not interpret <br>\n        newCell.innerHTML = content;\n      }\n      function spanCell_xx1zgyz6jocp066tk7px(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_xx1zgyz6jocp066tk7px\");\n        const targetRow = table.rows[i];\n        const targetCell = targetRow.cells[j];\n        for (let r = 0; r < rowspan; r++) {\n          // Only start deleting cells to the right for the first row (r == 0)\n          if (r === 0) {\n            // Delete cells to the right of the target cell in the first row\n            for (let c = colspan - 1; c > 0; c--) {\n              if (table.rows[i + r].cells[j + c]) {\n                table.rows[i + r].deleteCell(j + c);\n              }\n            }\n          }\n          // For rows below the first, delete starting from the target column\n          if (r > 0) {\n            for (let c = colspan - 1; c >= 0; c--) {\n              if (table.rows[i + r] && table.rows[i + r].cells[j]) {\n                table.rows[i + r].deleteCell(j);\n              }\n            }\n          }\n        }\n        // Set rowspan and colspan of the target cell\n        targetCell.rowSpan = rowspan;\n        targetCell.colSpan = colspan;\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: 1, j: 1 }, { i: 2, j: 1 }, { i: 3, j: 1 }, { i: 4, j: 1 }, { i: 5, j: 1 }, { i: 6, j: 1 }, { i: 7, j: 1 }, { i: 8, j: 1 }, { i: 9, j: 1 }, { i: 10, j: 1 }, { i: 11, j: 1 }, { i: 12, j: 1 }, { i: 13, j: 1 }, { i: 14, j: 1 }, { i: 15, j: 1 }, { i: 16, j: 1 }, { i: 17, j: 1 }, { i: 18, j: 1 }, { i: 19, j: 1 }, { i: 20, j: 1 }, { i: 21, j: 1 }, { i: 22, j: 1 }, { i: 23, j: 1 }, { i: 24, j: 1 }, { i: 25, j: 1 }, { i: 26, j: 1 }, { i: 27, j: 1 }, { i: 28, j: 1 }, { i: 29, j: 1 }, { i: 30, j: 1 }, { i: 31, j: 1 }, { i: 32, j: 1 }, { i: 33, j: 1 }, { i: 34, j: 1 }, { i: 35, j: 1 }, { i: 36, j: 1 }, { i: 37, j: 1 }, { i: 38, j: 1 }, { i: 39, j: 1 }, { i: 40, j: 1 }, { i: 41, j: 1 }, { i: 42, j: 1 }, { i: 43, j: 1 }, { i: 44, j: 1 }, { i: 45, j: 1 }, { i: 46, j: 1 }, { i: 47, j: 1 }, { i: 48, j: 1 }, { i: 49, j: 1 }, { i: 50, j: 1 }, { i: 51, j: 1 }, { i: 52, j: 1 }, { i: 53, j: 1 }, { i: 54, j: 1 }, { i: 55, j: 1 }, { i: 56, j: 1 }, { i: 57, j: 1 }, { i: 59, j: 1 }, { i: 60, j: 1 },  ], css_id: 'tinytable_css_tvbzzt33wj9xo32jdpsg',}, \n          { positions: [ { i: 58, j: 1 },  ], css_id: 'tinytable_css_putrptat5zdedcyjb59t',}, \n          { positions: [ { i: 0, j: 0 },  ], css_id: 'tinytable_css_jzp7ftfys0jiy2jpby25',}, \n          { positions: [ { i: 1, j: 0 }, { i: 2, j: 0 }, { i: 3, j: 0 }, { i: 4, j: 0 }, { i: 5, j: 0 }, { i: 6, j: 0 }, { i: 7, j: 0 }, { i: 8, j: 0 }, { i: 9, j: 0 }, { i: 10, j: 0 }, { i: 11, j: 0 }, { i: 12, j: 0 }, { i: 13, j: 0 }, { i: 14, j: 0 }, { i: 15, j: 0 }, { i: 16, j: 0 }, { i: 17, j: 0 }, { i: 18, j: 0 }, { i: 19, j: 0 }, { i: 20, j: 0 }, { i: 21, j: 0 }, { i: 22, j: 0 }, { i: 23, j: 0 }, { i: 24, j: 0 }, { i: 25, j: 0 }, { i: 26, j: 0 }, { i: 27, j: 0 }, { i: 28, j: 0 }, { i: 29, j: 0 }, { i: 30, j: 0 }, { i: 31, j: 0 }, { i: 32, j: 0 }, { i: 33, j: 0 }, { i: 34, j: 0 }, { i: 35, j: 0 }, { i: 36, j: 0 }, { i: 37, j: 0 }, { i: 38, j: 0 }, { i: 39, j: 0 }, { i: 40, j: 0 }, { i: 41, j: 0 }, { i: 42, j: 0 }, { i: 43, j: 0 }, { i: 44, j: 0 }, { i: 45, j: 0 }, { i: 46, j: 0 }, { i: 47, j: 0 }, { i: 48, j: 0 }, { i: 49, j: 0 }, { i: 50, j: 0 }, { i: 51, j: 0 }, { i: 52, j: 0 }, { i: 53, j: 0 }, { i: 54, j: 0 }, { i: 55, j: 0 }, { i: 56, j: 0 }, { i: 57, j: 0 }, { i: 59, j: 0 }, { i: 60, j: 0 },  ], css_id: 'tinytable_css_im2h0hwfn1rakvvoeiaj',}, \n          { positions: [ { i: 61, j: 0 },  ], css_id: 'tinytable_css_9p80jbh4o5bu8rojv03q',}, \n          { positions: [ { i: 0, j: 1 },  ], css_id: 'tinytable_css_7d4pbhqf403wx0c3dyia',}, \n          { positions: [ { i: 58, j: 0 },  ], css_id: 'tinytable_css_5yhcotgvua4h7lceuw6l',}, \n          { positions: [ { i: 61, j: 1 },  ], css_id: 'tinytable_css_35eo15dquags8x4qatjz',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_xx1zgyz6jocp066tk7px(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_tvbzzt33wj9xo32jdpsg, .table th.tinytable_css_tvbzzt33wj9xo32jdpsg { text-align: center; }\n      .table td.tinytable_css_putrptat5zdedcyjb59t, .table th.tinytable_css_putrptat5zdedcyjb59t { text-align: center; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_jzp7ftfys0jiy2jpby25, .table th.tinytable_css_jzp7ftfys0jiy2jpby25 { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_im2h0hwfn1rakvvoeiaj, .table th.tinytable_css_im2h0hwfn1rakvvoeiaj { text-align: left; }\n      .table td.tinytable_css_9p80jbh4o5bu8rojv03q, .table th.tinytable_css_9p80jbh4o5bu8rojv03q { text-align: left; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_7d4pbhqf403wx0c3dyia, .table th.tinytable_css_7d4pbhqf403wx0c3dyia { text-align: center; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_5yhcotgvua4h7lceuw6l, .table th.tinytable_css_5yhcotgvua4h7lceuw6l { text-align: left; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_35eo15dquags8x4qatjz, .table th.tinytable_css_35eo15dquags8x4qatjz { text-align: center; border-bottom: solid #d3d8dc 0.1em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_xx1zgyz6jocp066tk7px\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\"> </th>\n                <th scope=\"col\">(1)</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='2'>+ p < 0.1, * p < 0.05, ** p < 0.01, *** p < 0.001</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td>(Intercept)</td>\n                  <td>5.146***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.230)</td>\n                </tr>\n                <tr>\n                  <td>lrscale</td>\n                  <td>0.136**</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.048)</td>\n                </tr>\n                <tr>\n                  <td>country_name_FBelgium</td>\n                  <td>-0.550***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.012)</td>\n                </tr>\n                <tr>\n                  <td>country_name_FBulgaria</td>\n                  <td>-2.415***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.022)</td>\n                </tr>\n                <tr>\n                  <td>country_name_FCroatia</td>\n                  <td>-1.349***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.018)</td>\n                </tr>\n                <tr>\n                  <td>country_name_FCyprus</td>\n                  <td>-1.273***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.021)</td>\n                </tr>\n                <tr>\n                  <td>country_name_FFinland</td>\n                  <td>0.885***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.035)</td>\n                </tr>\n                <tr>\n                  <td>country_name_FFrance</td>\n                  <td>-1.531***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.010)</td>\n                </tr>\n                <tr>\n                  <td>country_name_FGermany</td>\n                  <td>-0.060***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.013)</td>\n                </tr>\n                <tr>\n                  <td>country_name_FGreece</td>\n                  <td>-1.620***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.023)</td>\n                </tr>\n                <tr>\n                  <td>country_name_FHungary</td>\n                  <td>-1.353***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.040)</td>\n                </tr>\n                <tr>\n                  <td>country_name_FIceland</td>\n                  <td>0.121***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.001)</td>\n                </tr>\n                <tr>\n                  <td>country_name_FIreland</td>\n                  <td>0.098***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.005)</td>\n                </tr>\n                <tr>\n                  <td>country_name_FIsrael</td>\n                  <td>-1.733***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.055)</td>\n                </tr>\n                <tr>\n                  <td>country_name_FItaly</td>\n                  <td>-0.736***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.016)</td>\n                </tr>\n                <tr>\n                  <td>country_name_FLatvia</td>\n                  <td>-1.313***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.052)</td>\n                </tr>\n                <tr>\n                  <td>country_name_FLithuania</td>\n                  <td>-1.003***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.019)</td>\n                </tr>\n                <tr>\n                  <td>country_name_FMontenegro</td>\n                  <td>-1.307***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.029)</td>\n                </tr>\n                <tr>\n                  <td>country_name_FNetherlands</td>\n                  <td>0.172***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.010)</td>\n                </tr>\n                <tr>\n                  <td>country_name_FNorway</td>\n                  <td>1.343***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.015)</td>\n                </tr>\n                <tr>\n                  <td>country_name_FPoland</td>\n                  <td>-0.672***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.034)</td>\n                </tr>\n                <tr>\n                  <td>country_name_FPortugal</td>\n                  <td>-0.946***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.005)</td>\n                </tr>\n                <tr>\n                  <td>country_name_FSerbia</td>\n                  <td>-1.741***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.008)</td>\n                </tr>\n                <tr>\n                  <td>country_name_FSlovakia</td>\n                  <td>-1.230***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.014)</td>\n                </tr>\n                <tr>\n                  <td>country_name_FSlovenia</td>\n                  <td>-0.811***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.003)</td>\n                </tr>\n                <tr>\n                  <td>country_name_FSpain</td>\n                  <td>-1.019***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.008)</td>\n                </tr>\n                <tr>\n                  <td>country_name_FSweden</td>\n                  <td>0.799***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.002)</td>\n                </tr>\n                <tr>\n                  <td>country_name_FSwitzerland</td>\n                  <td>1.710***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.011)</td>\n                </tr>\n                <tr>\n                  <td>country_name_FUnited Kingdom</td>\n                  <td>-1.327***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.008)</td>\n                </tr>\n                <tr>\n                  <td>Num.Obs.</td>\n                  <td>39522</td>\n                </tr>\n                <tr>\n                  <td>R2</td>\n                  <td>0.160</td>\n                </tr>\n                <tr>\n                  <td>R2 Adj.</td>\n                  <td>0.160</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\n`vcov = \\~country_name_F`\n\n:   Met deze optie vragen we om geclusterde standaardfouten te berekenen voor ons model. De clustervariabele moet aangeduid worden in de syntax.\n\nWe kunnen de `vcov` optie ook gebruiken voor voorspellingen en marginal effects binnen de `avg_slopes` en `predictions` functies:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredictions(demsatis_model2, \n            newdata = datagrid(lrscale = c(0:10)), \n            vcov = ~country_name_F) |> \n  ggplot(aes(x = lrscale, y = estimate)) + \n  geom_line() + \n  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = 0.2) + \n  theme_bw() + \n  labs(title = \"Voorspelde waarden met geclusterde standaardfouten\", \n       x = \"Links-rechtspositionering\", \n       y = \"Voorspelde tevredenheid met democratie\") + \n  scale_x_continuous(breaks = c(0:10)) + \n  scale_y_continuous(limits = c(0,10))\n```\n\n::: {.cell-output-display}\n![](errors_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n\n::: callout-important\n#### Presentatie\n\nMet de `modelsummary` functie hierboven creëerden we een regressietabel met de coëfficiënten voor alle \\`country_name_F'- categorieën. Als er echter heel veel dummies zijn (en die dummies zijn ook minder relevant voor de interpetatie), dan worden ze vaak weggelaten in de output. Wel moet je in de notitie aan de lezer verduidelijken dat 'fixed effects' en geclusterde standaardfouten werden gebruikt.\n\nWe gebruiken `coef_map` om bepaalde coëfficiënten weg te kunnen laten in de output (zie @sec-interaction-term-in-a-regression-table).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelsummary(\n  demsatis_model2, \n  stars = T, \n  vcov = ~country_name_F, \n  coef_map = c(\"(Intercept)\" = \"Constante\", \n               \"lrscale\" = \"Links-Rechtspositie\"),\n  gof_map = c(\"nobs\", \"r.squared\", \"adj.r.squared\"),\n  title = \"Democratische tevredenheid en links-rechtspositie\", \n  notes = \"Lineaire regressiecoëfficiënten met geclusterde standaardfouten tussen haakjes. Model geschat met country fixed effects.\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_yn137h4nw1okh9tjtoq2(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_yn137h4nw1okh9tjtoq2\");\n          var cell = table.rows[i]?.cells[j];  // Safe navigation to avoid errors\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function insertSpanRow(i, colspan, content) {\n        var table = document.getElementById('tinytable_yn137h4nw1okh9tjtoq2');\n        var newRow = table.insertRow(i);\n        var newCell = newRow.insertCell(0);\n        newCell.setAttribute(\"colspan\", colspan);\n        // newCell.innerText = content;\n        // this may be unsafe, but innerText does not interpret <br>\n        newCell.innerHTML = content;\n      }\n      function spanCell_yn137h4nw1okh9tjtoq2(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_yn137h4nw1okh9tjtoq2\");\n        const targetRow = table.rows[i];\n        const targetCell = targetRow.cells[j];\n        for (let r = 0; r < rowspan; r++) {\n          // Only start deleting cells to the right for the first row (r == 0)\n          if (r === 0) {\n            // Delete cells to the right of the target cell in the first row\n            for (let c = colspan - 1; c > 0; c--) {\n              if (table.rows[i + r].cells[j + c]) {\n                table.rows[i + r].deleteCell(j + c);\n              }\n            }\n          }\n          // For rows below the first, delete starting from the target column\n          if (r > 0) {\n            for (let c = colspan - 1; c >= 0; c--) {\n              if (table.rows[i + r] && table.rows[i + r].cells[j]) {\n                table.rows[i + r].deleteCell(j);\n              }\n            }\n          }\n        }\n        // Set rowspan and colspan of the target cell\n        targetCell.rowSpan = rowspan;\n        targetCell.colSpan = colspan;\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: 4, j: 0 },  ], css_id: 'tinytable_css_zatv4rlfeo9pgwk26yg2',}, \n          { positions: [ { i: 0, j: 0 },  ], css_id: 'tinytable_css_oqjilux1acgoeuphsd0i',}, \n          { positions: [ { i: 4, j: 1 },  ], css_id: 'tinytable_css_nfdpr347apx19acbnvzh',}, \n          { positions: [ { i: 7, j: 0 },  ], css_id: 'tinytable_css_m2gmcyg3w5bgzcca4j2p',}, \n          { positions: [ { i: 7, j: 1 },  ], css_id: 'tinytable_css_kjnk3x6u60yz57sfr704',}, \n          { positions: [ { i: 1, j: 1 }, { i: 2, j: 1 }, { i: 3, j: 1 }, { i: 5, j: 1 }, { i: 6, j: 1 },  ], css_id: 'tinytable_css_gg4makszpdjmi6m4ewzl',}, \n          { positions: [ { i: 1, j: 0 }, { i: 2, j: 0 }, { i: 3, j: 0 }, { i: 5, j: 0 }, { i: 6, j: 0 },  ], css_id: 'tinytable_css_d3aces497msv74tq9z35',}, \n          { positions: [ { i: 0, j: 1 },  ], css_id: 'tinytable_css_2vgg7kk56wew2oua9xzf',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_yn137h4nw1okh9tjtoq2(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_zatv4rlfeo9pgwk26yg2, .table th.tinytable_css_zatv4rlfeo9pgwk26yg2 { text-align: left; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_oqjilux1acgoeuphsd0i, .table th.tinytable_css_oqjilux1acgoeuphsd0i { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_nfdpr347apx19acbnvzh, .table th.tinytable_css_nfdpr347apx19acbnvzh { text-align: center; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_m2gmcyg3w5bgzcca4j2p, .table th.tinytable_css_m2gmcyg3w5bgzcca4j2p { text-align: left; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_kjnk3x6u60yz57sfr704, .table th.tinytable_css_kjnk3x6u60yz57sfr704 { text-align: center; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_gg4makszpdjmi6m4ewzl, .table th.tinytable_css_gg4makszpdjmi6m4ewzl { text-align: center; }\n      .table td.tinytable_css_d3aces497msv74tq9z35, .table th.tinytable_css_d3aces497msv74tq9z35 { text-align: left; }\n      .table td.tinytable_css_2vgg7kk56wew2oua9xzf, .table th.tinytable_css_2vgg7kk56wew2oua9xzf { text-align: center; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_yn137h4nw1okh9tjtoq2\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        <caption>Democratische tevredenheid en links-rechtspositie</caption>\n              <tr>\n                <th scope=\"col\"> </th>\n                <th scope=\"col\">(1)</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='2'>+ p < 0.1, * p < 0.05, ** p < 0.01, *** p < 0.001</td></tr>\n<tr><td colspan='2'>Lineaire regressiecoëfficiënten met geclusterde standaardfouten tussen haakjes. Model geschat met country fixed effects.</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td>Constante</td>\n                  <td>5.146***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.230)</td>\n                </tr>\n                <tr>\n                  <td>Links-Rechtspositie</td>\n                  <td>0.136**</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.048)</td>\n                </tr>\n                <tr>\n                  <td>Num.Obs.</td>\n                  <td>39522</td>\n                </tr>\n                <tr>\n                  <td>R2</td>\n                  <td>0.160</td>\n                </tr>\n                <tr>\n                  <td>R2 Adj.</td>\n                  <td>0.160</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n:::\n\n### Probleem 2: Data over de tijd heen en seriële autocorrelatie\n\nDe assumptie van onafhankelijke fouten kan ook geschonden worden als we dezelfde eenheid (bv. een persoon, land, bedrijf) observeren over meerder punten in de tijd. Dit wordt 'time-series' data genoemd.\n\nStel bijvoorbeeld dat we geïnteresseerd zijn in de relatie tussen welvaart en democratie in een land. We maken hier gebruik van V-Dem data en kijken naar de relatie tussen welvaart van een land (`e_gdp`) en democratiescore (`v2x_polyarchy`). We richten ons eerst op Nederland. Hieronder tonen we hoe de data eruit ziet.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Filteren op Nederland\nnetherlands <- serial_data |> \n  filter(country_name == \"Netherlands\")\n\n#eerste 15 rijen in de dataset bekijken\nhead(netherlands, n = 15L)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   country_name year v2x_polyarchy    e_gdp\n1   Netherlands 1789         0.076 2309.141\n2   Netherlands 1790         0.076 2362.091\n3   Netherlands 1791         0.076 2411.786\n4   Netherlands 1792         0.076 2454.337\n5   Netherlands 1793         0.076 2481.157\n6   Netherlands 1794         0.076 2485.290\n7   Netherlands 1795         0.097 2463.161\n8   Netherlands 1796         0.133 2486.460\n9   Netherlands 1797         0.181 2491.454\n10  Netherlands 1798         0.179 2447.313\n11  Netherlands 1799         0.127 2358.512\n12  Netherlands 1800         0.127 2249.312\n13  Netherlands 1801         0.127 2283.304\n14  Netherlands 1802         0.127 2304.492\n15  Netherlands 1803         0.127 2283.129\n```\n\n\n:::\n:::\n\n\n\nDe dataset meet de variabelen vanaf 1789. Maar vinden we een relatie tussen de twee variabelen? Gaat hogere welvaart gepaard met meer democratie? We kunnen een lineaire regressie schatten om dit te proberen nagaan. We beperken ons hier tot een bivariate analyse. In de praktijk zou je ook op zoek willen gaan naar controlevariabelen.[^errors-6]\n\n[^errors-6]: Als we ons richten op controlevariabelen in het geval van 1 land dan moeten deze variëren over de tijd in Nederland (time-variant) en niet vaststaan (time-invariant).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Het model\nneth_model1 <- lm(v2x_polyarchy ~ e_gdp, data = netherlands)\n\n# Coëfficiënt bekijken\ntidy(neth_model1, conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 7\n  term          estimate   std.error statistic  p.value   conf.low  conf.high\n  <chr>            <dbl>       <dbl>     <dbl>    <dbl>      <dbl>      <dbl>\n1 (Intercept) 0.355      0.0166           21.4 2.14e-56 0.323      0.388     \n2 e_gdp       0.00000384 0.000000255      15.0 5.82e-36 0.00000334 0.00000434\n```\n\n\n:::\n:::\n\n\n\nDe coëfficiënt voor `e_gdp` is positief. Het getal is erg klein, maar dit betekent niet noodzakelijk een klein effect gezien de predictor hier een sterke spreiding heeft. De coëfficiënt is ook statistisch significant.\n\nEchter moeten we opletten: onze observaties zijn allemaal gelinkt aan hetzelfde land en zijn dus niet onafhankelijk. Dit betekent vaak dat we de standaardfouten onderschatten en we kunnen zo onterecht significate effecten vinden.\n\nDit probleem is gekend als seriële autocorrelatie: de errors van het model zijn gecorreleerd met elkaar over de tijd heen. Een error op tijdstip *t* is systematisch gerelateerd aan de error van het jaar voordien, *t-1*. Dit is logisch gezien de welvaart en het democratisch gehalte van een land vrij stabiel zijn en afhangen van onderliggende condities zoals economische instituties, natuurlijke rijkdommen enz. Deze factoren fluctueren niet zo sterk over de tijd heen waardoor opeenvolgende errors vaak lijken op elkaar.\n\nWe kunnen formeel nagaan of er seriële autocorrelatie aanwezig is met behulp van de Durbin-Watson statistiek zoals besproken in @sec-ols-assumptions.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncar::durbinWatsonTest(neth_model1) #<1>\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n lag Autocorrelation D-W Statistic p-value\n   1       0.9667039    0.05304265       0\n Alternative hypothesis: rho != 0\n```\n\n\n:::\n:::\n\n\n\n1.  Het `car::` prefix staat ons hier toe om het `car`package te gebruiken zonder het te moeten laden. Dit heeft voordelen gezien `car`ook funties heeft die conflicteren met andere functies die we gebruiken, in het bijzonder de `recode` functie uit het `dplyr`/`tidyverse` package.\n\nDe Autocorrelation kolom geeft de correlatie weer tussen errors van het ene jaar op het andere. De correlatie is 0.97. Dit is hoog, gezien het maximum +1 is. De D-W Statistic test formeel of de autocorrelatie te hoog is. Dit is het geval als D-W hoger is dan 3 of kleiner dan 1. Hier is het duidelijk lager dan 1 (0.053). De p-waarde is extreem klein en dus verwerpen we de nulhypothese dat er geen autocorrelatie is. De standaardfouten zijn niet correct.\n\nWe kunnen dit probleem oplossen door een 'vertraagde afhankelijke variabele' ('lagged dependent variable') toe te voegen als predictor in ons model. Deze vertraagde afhankelijke variabele bevat voor elke observatie de score voor de afhankelijke variabele in het onmiddellijk voorgaande tijdspunt. Door deze variabele op te nemen wordt het probleem van stabiliteit/inertie in de afhankelijke variabele (en gecorreleerde errors) verholpen.[^errors-7]\n\n[^errors-7]: Er zijn nog andere manieren om dergelijke time series te modelleren, maar deze zijn te gevorderd voor dit handboek.\n\n#### Lagged Dependent Variables maken\n\nWe kunnen de `lag()` functie gebruiken om onze afhankelijke variabele te 'vertragen' voor een nieuw aangemaakte variabele.[^errors-8]\n\n[^errors-8]: Hier maken we een vertraagde afhankelijke variable maar hetzelfde proces kan gebruikt worden voor *onafhankelijke* variabelen, bijvoorbeeld als er zorgen zijn over omgekeerde causale verbanden ('reverse causality').\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnetherlands <- netherlands |> \n  mutate(dem_lag = lag(v2x_polyarchy, 1))\n```\n:::\n\n\n\n`lag(v2x_polyarchy, 1)`\n\n:   We gebruiken de functie `lag` op de relevante afhankelijke variabele (hier, `v2x_polyarchy`). Het nummer aan het einde van de functie geeft weer hoeveel eenheden vertraging we willen. Met het cijfer 1 zeggen we 1 tijdseenheid (hier: 1 jaar). Dit is het meest gebruikelijk. Indien we de `v2x_polyarchy` score van 2 jaar terug zouden willen, dan schrijven we '2' enzovoort.\n\nLaten we even kijken wat dat doet:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(netherlands, n = 15L)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   country_name year v2x_polyarchy    e_gdp dem_lag\n1   Netherlands 1789         0.076 2309.141      NA\n2   Netherlands 1790         0.076 2362.091   0.076\n3   Netherlands 1791         0.076 2411.786   0.076\n4   Netherlands 1792         0.076 2454.337   0.076\n5   Netherlands 1793         0.076 2481.157   0.076\n6   Netherlands 1794         0.076 2485.290   0.076\n7   Netherlands 1795         0.097 2463.161   0.076\n8   Netherlands 1796         0.133 2486.460   0.097\n9   Netherlands 1797         0.181 2491.454   0.133\n10  Netherlands 1798         0.179 2447.313   0.181\n11  Netherlands 1799         0.127 2358.512   0.179\n12  Netherlands 1800         0.127 2249.312   0.127\n13  Netherlands 1801         0.127 2283.304   0.127\n14  Netherlands 1802         0.127 2304.492   0.127\n15  Netherlands 1803         0.127 2283.129   0.127\n```\n\n\n:::\n:::\n\n\n\nElke rij in de dataset bevat waarden per uniek jaar (1789, 1790, ...). `v2x_polyarchy` geeft de democratiescore van het land in het betreffende jaar. De nieuwe kolom (`dem_lag`) geeft de score in het *voorgaande jaar*. De waarde voor `dem_lag` in rij 9 (year = 1797) is 0.133; dis was de waarde voor democratie in 1796 (rij 8).We zien NA in de eerste rij gezien we geen voorgaande data hebben.\n\n::: callout-important\n#### Waarschuwing!\n\nHet spreekt voor zich dat de dataset eerst netjes geordend moet zijn op jaar vooraleer we functies zoals `car::durbinWatsonTest`en `lag` kunnen gebruiken. Hoe je een dataset kan ordenen (indien nodig) wordt besproken in @sec-ols-assumptions.\n:::\n\nWe voegen nu de lagged dependent variabele toe als predictor aan ons origineel model\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Het nieuwe model\nneth_model2 <- lm(v2x_polyarchy ~ e_gdp + dem_lag, data = netherlands)\n\n# Coëfficiënten opvragen\ntidy(neth_model2, conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 7\n  term            estimate    std.error statistic   p.value   conf.low conf.high\n  <chr>              <dbl>        <dbl>     <dbl>     <dbl>      <dbl>     <dbl>\n1 (Intercept) 0.0121       0.00667          1.81  7.20e-  2   -1.09e-3   2.52e-2\n2 e_gdp       0.0000000561 0.0000000838     0.669 5.04e-  1   -1.09e-7   2.21e-7\n3 dem_lag     0.978        0.0155          63.3   2.53e-145    9.48e-1   1.01e+0\n```\n\n\n:::\n\n```{.r .cell-code}\n#Opvragen model fit statistieken via broom::glance()\nglance(neth_model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 12\n  r.squared adj.r.squared  sigma statistic   p.value    df logLik   AIC   BIC\n      <dbl>         <dbl>  <dbl>     <dbl>     <dbl> <dbl>  <dbl> <dbl> <dbl>\n1     0.973         0.973 0.0486     4110. 7.47e-178     2   367. -727. -713.\n# ℹ 3 more variables: deviance <dbl>, df.residual <int>, nobs <int>\n```\n\n\n:::\n:::\n\n\n\nDe coëfficiënt voor `dem_lag` is 0.978. Dit is hoog, onze afhankelijke variabele heeft een bereik van 0 tot 1. De coëfficiënt toont dus dat er sterke stabiliteit is tussen democratiescores in opeenvolgende jaren. [^errors-9] We vinden dan ook dat de R^2^ statistieken dichtbij hun maxima van 1 zitten: toevoeging van de lagged dependent variable verklaart bijna alle variatie in democratiescore.\n\n[^errors-9]: De bivariate pearson correlatie tussen de twee variabelen is 0.99. Democratiescores in Nederland blijven erg stabiel van jaar tot jaar.\n\nDe coëfficiënt voor `e_gdp` toont de associate tussen BBP en democratiescores gecontroleerd voor democratiescore in het voorgaande jaar. Dit vertelt ons eigenlijk of BBP gerelataard is aan *verandering in democratiescore* van jaar tot jaar. De coëfficiënt is positief, maar niet langer significant.\n\nHebben we daarmee het probleem van autocorrelatie opgelost? We gaan het na:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncar::durbinWatsonTest(neth_model2) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n lag Autocorrelation D-W Statistic p-value\n   1       0.2865016      1.425975   0.006\n Alternative hypothesis: rho != 0\n```\n\n\n:::\n:::\n\n\n\nAutocorrelatie bedraagt nu slechts 0.29, wat veel lager is dan de 0.97 in het voorgaande model. De D-W statistiek bevindt zich nu tussen 1 en 3. Er is nog autocorrelatie (zie de ook de p-waarde), maar we hebben al veel in rekening gebracht.\n\nVoorgaand voorbeeld was gericht op 1 land, namelijk Nederland. In het geval we meerdere landen hebben kunnen we ook de `lag` functie gebruiken, maar er zal wel een probleem optreden waar we ons van bewust moeten zijn. We tonen eerst wat het probleem is en bieden dan een oplossing:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nserial_data |> \n  mutate(dem_lag = lag(v2x_polyarchy)) |> \n  slice(225:235) # <1>\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   country_name year v2x_polyarchy      e_gdp dem_lag\n1        Mexico 2013         0.623 423815.579   0.649\n2        Mexico 2014         0.620 429987.309   0.623\n3        Mexico 2015         0.639 432220.100   0.620\n4        Mexico 2016         0.640 440041.959   0.639\n5        Mexico 2017         0.635 449152.118   0.640\n6        Mexico 2018         0.675 455569.106   0.635\n7        Mexico 2019         0.685 456743.982   0.675\n8      Suriname 1960         0.526    237.768   0.685\n9      Suriname 1961         0.526    244.437   0.526\n10     Suriname 1962         0.526    255.809   0.526\n11     Suriname 1963         0.527    272.408   0.526\n```\n\n\n:::\n:::\n\n\n\n1.  Deze syntax vraagt R om de data te 'snijden' en data te tonen voor rij 225 tot en met 235.\n\nWe tonen hier de transitie in de dataset van Mexico naar Suriname. In rij 7 bevind zich de data voor Mexico voor het laats beschikbare jaar 2019. Dan springt de dataset naar het eerste jaar voor Suriname, namelijk 1960. Als we kijken naar de `dem_lag` variabele zien we dat Suriname in 1960 de democratiescore van Mexico in 2019 heeft meegekregen. Dat mag natuurlijk niet. Zonder correctie doet R dit voor alle punten in de dataset waar we van 1 land naar een ander land gaan.\n\nWe vermijden dit door de `group_by()` functie te gebruiken:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nserial_data <- serial_data |> \n  group_by(country_name) |> \n  mutate(dem_lag = lag(v2x_polyarchy)) |> \n  ungroup() \n```\n:::\n\n\n\n`group_by(country_name)`\n\n:   De `group_by()` functie vraagt R om de dataset eerst te groeperen volgens de variabele tussen haakjes (hier: country_name). Daarna pas wordt de `lag`functie, via `mutate()`, toegepast. Wat er precies gebeurt kun je zien met deze gif van [Andrew Heiss](https://www.andrewheiss.com/blog/2024/04/04/group_by-summarize-ungroup-animations/){target=\"_blank\"} [-@heiss2024]:\n\n\n\n{{< video figures/grp-mutate.mp4 >}}\n\n\n\n\n`ungroup()`\n\n:   Deze functie is nodig om `mutate` te vertellen dat we niet langer willen groeperen voor toekomstige toepassingen van de functie. Anders blijft `mutate` verdere bewerkingen per groep uitvoeren.\n\nLaten we bekijken wat er gebeurt is\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nserial_data |> \n  slice(225:235)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 11 × 5\n   country_name  year v2x_polyarchy   e_gdp dem_lag\n   <chr>        <dbl>         <dbl>   <dbl>   <dbl>\n 1 Mexico        2013         0.623 423816.   0.649\n 2 Mexico        2014         0.62  429987.   0.623\n 3 Mexico        2015         0.639 432220.   0.62 \n 4 Mexico        2016         0.64  440042.   0.639\n 5 Mexico        2017         0.635 449152.   0.64 \n 6 Mexico        2018         0.675 455569.   0.635\n 7 Mexico        2019         0.685 456744.   0.675\n 8 Suriname      1960         0.526    238.  NA    \n 9 Suriname      1961         0.526    244.   0.526\n10 Suriname      1962         0.526    256.   0.526\n11 Suriname      1963         0.527    272.   0.526\n```\n\n\n:::\n:::\n\n\n\nWe zien nu een NA waarde in rij 8, het eerste beschikbare jaar voor Suriname. Dit is wat we willen.\n\nWe zouden nu de regressie opnieuw kunnen uitvoeren. Onze dataset heeft nu echter niet alleen een time series element, maar bevat ook geclusterde data want meerdere landen zijn opgenomen. We zullen de lagged dependent variable-techniek dus moeten combineren met bovenstaande technieken voor clustering (fixed effects en geclusterde standaardfouten).\n\n## Omgaan met niet-normaal verdeelde residuals\n\n### Wat was het probleem ook al weer?\n\nDe laatste assumptie die we hier bekijken stelt dat de errors/residuals/fouten in een OLS model normaal verdeeld zijn. Of aan deze assumptie voldaan is kunnen we nagaan met plots gemaakt via `resid_panel()`: een histogram van de residuals en een Q-Q plot van de residuals.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model schatten\nnorm_model <- lm(v2x_polyarchy ~ gini_disp + pr_fct + region1, data = normal_residual_data)\n\n# Coëfficiënten opvragen\ntidy(norm_model, conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 7\n  term            estimate std.error statistic p.value conf.low conf.high\n  <chr>              <dbl>     <dbl>     <dbl>   <dbl>    <dbl>     <dbl>\n1 (Intercept)      0.641     0.195       3.29  0.00154   0.253    1.03   \n2 gini_disp       -0.00492   0.00531    -0.928 0.357    -0.0155   0.00566\n3 pr_fctPR System  0.0831    0.0619      1.34  0.184    -0.0404   0.207  \n4 region1Africa   -0.0940    0.114      -0.824 0.413    -0.321    0.133  \n5 region1Europe    0.176     0.0665      2.65  0.00997   0.0435   0.309  \n6 region1Americas  0.168     0.0710      2.37  0.0207    0.0265   0.310  \n```\n\n\n:::\n\n```{.r .cell-code}\n# Assumptie checken\nresid_panel(norm_model, plots = c(\"hist\", \"qq\"))\n```\n\n::: {.cell-output-display}\n![](errors_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\n\nBeide grafieken leiden tot dezelfde vaststelling: de assumptie is geschonden (zie @sec-ols-assumptions). Met een relatief grote steekproef is een schending van deze assumptie doorgaans geen probleem. In kleine steekproeven kan dit wel problematisch zijn. Hier zien we met de `glance()` functie uit het `broom` package dat we met een kleine steekproef te maken hebben:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglance(norm_model)$nobs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 77\n```\n\n\n:::\n:::\n\n\n\nWe hebben 77 observaties in het model. Is dit klein of groot genoeg? Jammergenoeg bestaat hier geen eenduidig antwoord voor. Een vuistregel is dat we met een kleine steekproef te maken hebben bij minder dan 15 observaties per onafhankelijke variabele. Hier hebben we 5 predictors. We vinden dan dat we met 77 observaties net 2 meer hebben dan de vuistregel voorschrijft (5 \\* 15 = 75). Dit is echter dicht bij de grens, dus misschien is het toch veiliger om rekening te houden met een assumptieschending.\n\n### Mogelijke oplossing: bootstrapping\n\nOok voor een schending van deze assumptie (met een kleine steekproef) moeten we de standaardfouten herberekenen. We gebruiken in dit geval weer een andere herberekening dan hierboven, namelijk 'gebootstrapte' standaardfouten. Met bootstrapping worden standaardfouten herschat met de volgende procedure:\n\nWe nemen een steekproef van de oorspronkelijke steekproef met dezelfde grootte. Dit gebeurt met teruglegging van de observaties, dat wil zeggen 1 observatie kan meerdere malen opgenomen worden in de nieuwe steekproef. Dat moet natuurlijk, anders kom je gewoon telkens dezelfde steekproef uit. Op basis van de nieuwe steekproef schatten we coëfficiënt en standaardfout opnieuw en slagen de resultaten op. Dit doen we een aantal keren. Ten slotte kijken we naar alle verschillende coëfficiënten die we uitgekomen zijn en in het bijzonder naar de standaardafwijking van de verzameling coëfficiënten. Deze standaardafwijking wordt de 'gebootstrapte'standaardfout.\n\nOok deze standaardfout kunnen we bekomen met de `vcov=` optie in de `modelsummary()` syntax. Wat nieuw is hier is dat we een element van toeval toevoegen in de berekening: R gaat 'random' nieuwe steekproeven trekken. Op zich is dit goed -moeten wij het niet doen!- maar juist door dit toevalselement kan de uitkomst telkens licht anders zijn. Om resultaten reproduceerbaar te houden zetten we hier dan ook een 'seed': een seed is een zelfgekozen startgeval (je kan 1 gebruiken maar ook je verjaardag enz.). Met de seed houdt R bij welke steekproeven precies getrokken werden en worden telkens dezelfde resultaten bereikt. Voor je je seed vastlegt wil je wel eerst nagaan of je met hetzelfde aantal steekproeven sterk verschillende resultaten uitkomt, want in dat geval vraag je R best meer steekproeven te trekken voor betere schattingen, zie onder).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# seed vastleggen\nset.seed(1)\n\n# Model schatten \nmodelsummary(norm_model, \n             stars = T, \n             vcov = \"bootstrap\", \n             gof_map = c(\"nobs\", \"r.squared\", \"adj.r.squared\"))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_vkmafstgktf1dfxmi2aw(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_vkmafstgktf1dfxmi2aw\");\n          var cell = table.rows[i]?.cells[j];  // Safe navigation to avoid errors\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function insertSpanRow(i, colspan, content) {\n        var table = document.getElementById('tinytable_vkmafstgktf1dfxmi2aw');\n        var newRow = table.insertRow(i);\n        var newCell = newRow.insertCell(0);\n        newCell.setAttribute(\"colspan\", colspan);\n        // newCell.innerText = content;\n        // this may be unsafe, but innerText does not interpret <br>\n        newCell.innerHTML = content;\n      }\n      function spanCell_vkmafstgktf1dfxmi2aw(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_vkmafstgktf1dfxmi2aw\");\n        const targetRow = table.rows[i];\n        const targetCell = targetRow.cells[j];\n        for (let r = 0; r < rowspan; r++) {\n          // Only start deleting cells to the right for the first row (r == 0)\n          if (r === 0) {\n            // Delete cells to the right of the target cell in the first row\n            for (let c = colspan - 1; c > 0; c--) {\n              if (table.rows[i + r].cells[j + c]) {\n                table.rows[i + r].deleteCell(j + c);\n              }\n            }\n          }\n          // For rows below the first, delete starting from the target column\n          if (r > 0) {\n            for (let c = colspan - 1; c >= 0; c--) {\n              if (table.rows[i + r] && table.rows[i + r].cells[j]) {\n                table.rows[i + r].deleteCell(j);\n              }\n            }\n          }\n        }\n        // Set rowspan and colspan of the target cell\n        targetCell.rowSpan = rowspan;\n        targetCell.colSpan = colspan;\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: 1, j: 0 }, { i: 2, j: 0 }, { i: 3, j: 0 }, { i: 4, j: 0 }, { i: 5, j: 0 }, { i: 6, j: 0 }, { i: 7, j: 0 }, { i: 8, j: 0 }, { i: 9, j: 0 }, { i: 10, j: 0 }, { i: 11, j: 0 }, { i: 13, j: 0 }, { i: 14, j: 0 },  ], css_id: 'tinytable_css_z43uej0t66jeh1refrc6',}, \n          { positions: [ { i: 1, j: 1 }, { i: 2, j: 1 }, { i: 3, j: 1 }, { i: 4, j: 1 }, { i: 5, j: 1 }, { i: 6, j: 1 }, { i: 7, j: 1 }, { i: 8, j: 1 }, { i: 9, j: 1 }, { i: 10, j: 1 }, { i: 11, j: 1 }, { i: 13, j: 1 }, { i: 14, j: 1 },  ], css_id: 'tinytable_css_ytbuf0plygvhzzysw9z0',}, \n          { positions: [ { i: 12, j: 1 },  ], css_id: 'tinytable_css_ro04r08jmmtxibs19y6v',}, \n          { positions: [ { i: 15, j: 0 },  ], css_id: 'tinytable_css_qa6kl0u3f3x17nwkzwen',}, \n          { positions: [ { i: 0, j: 1 },  ], css_id: 'tinytable_css_linihbawaah4imiuabqj',}, \n          { positions: [ { i: 12, j: 0 },  ], css_id: 'tinytable_css_9huqanmwbj5uzp9624ai',}, \n          { positions: [ { i: 15, j: 1 },  ], css_id: 'tinytable_css_7fsjl6dv4ltl5j6j30x1',}, \n          { positions: [ { i: 0, j: 0 },  ], css_id: 'tinytable_css_6fzz71m70kygs9j5evn3',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_vkmafstgktf1dfxmi2aw(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_z43uej0t66jeh1refrc6, .table th.tinytable_css_z43uej0t66jeh1refrc6 { text-align: left; }\n      .table td.tinytable_css_ytbuf0plygvhzzysw9z0, .table th.tinytable_css_ytbuf0plygvhzzysw9z0 { text-align: center; }\n      .table td.tinytable_css_ro04r08jmmtxibs19y6v, .table th.tinytable_css_ro04r08jmmtxibs19y6v { text-align: center; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_qa6kl0u3f3x17nwkzwen, .table th.tinytable_css_qa6kl0u3f3x17nwkzwen { text-align: left; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_linihbawaah4imiuabqj, .table th.tinytable_css_linihbawaah4imiuabqj { text-align: center; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_9huqanmwbj5uzp9624ai, .table th.tinytable_css_9huqanmwbj5uzp9624ai { text-align: left; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_7fsjl6dv4ltl5j6j30x1, .table th.tinytable_css_7fsjl6dv4ltl5j6j30x1 { text-align: center; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_6fzz71m70kygs9j5evn3, .table th.tinytable_css_6fzz71m70kygs9j5evn3 { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_vkmafstgktf1dfxmi2aw\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\"> </th>\n                <th scope=\"col\">(1)</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='2'>+ p < 0.1, * p < 0.05, ** p < 0.01, *** p < 0.001</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td>(Intercept)</td>\n                  <td>0.641**</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.230)</td>\n                </tr>\n                <tr>\n                  <td>gini_disp</td>\n                  <td>-0.005</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.006)</td>\n                </tr>\n                <tr>\n                  <td>pr_fctPR System</td>\n                  <td>0.083</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.082)</td>\n                </tr>\n                <tr>\n                  <td>region1Africa</td>\n                  <td>-0.094</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.100)</td>\n                </tr>\n                <tr>\n                  <td>region1Europe</td>\n                  <td>0.176*</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.079)</td>\n                </tr>\n                <tr>\n                  <td>region1Americas</td>\n                  <td>0.168*</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.080)</td>\n                </tr>\n                <tr>\n                  <td>Num.Obs.</td>\n                  <td>77</td>\n                </tr>\n                <tr>\n                  <td>R2</td>\n                  <td>0.305</td>\n                </tr>\n                <tr>\n                  <td>R2 Adj.</td>\n                  <td>0.256</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\n`set.seed(1)`\n\n:   We zetten het toevallig trekken van steekproeven hier vast met een zelfgekozen getal zodat resultaten dezelfde blijven.\n\n`vcov = \"boostrap\"`\n\n:   Deze optie vraagt om de 'gebootstrapte' standaarfouten.\n\nWe kunnen de standaardfouten vergelijken:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Seed: zelfde als hierboven want dan krijgen we zelfde resultaten\nset.seed(1)\n\n# Modellen vergelijken\nmodelsummary(norm_model, \n             stars = T, \n             vcov = c(\"classical\", \"bootstrap\"),\n             gof_map = c(\"nobs\", \"r.squared\", \"adj.r.squared\"))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_vkmafstgktf1dfxmi2aw(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_vkmafstgktf1dfxmi2aw\");\n          var cell = table.rows[i]?.cells[j];  // Safe navigation to avoid errors\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function insertSpanRow(i, colspan, content) {\n        var table = document.getElementById('tinytable_vkmafstgktf1dfxmi2aw');\n        var newRow = table.insertRow(i);\n        var newCell = newRow.insertCell(0);\n        newCell.setAttribute(\"colspan\", colspan);\n        // newCell.innerText = content;\n        // this may be unsafe, but innerText does not interpret <br>\n        newCell.innerHTML = content;\n      }\n      function spanCell_vkmafstgktf1dfxmi2aw(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_vkmafstgktf1dfxmi2aw\");\n        const targetRow = table.rows[i];\n        const targetCell = targetRow.cells[j];\n        for (let r = 0; r < rowspan; r++) {\n          // Only start deleting cells to the right for the first row (r == 0)\n          if (r === 0) {\n            // Delete cells to the right of the target cell in the first row\n            for (let c = colspan - 1; c > 0; c--) {\n              if (table.rows[i + r].cells[j + c]) {\n                table.rows[i + r].deleteCell(j + c);\n              }\n            }\n          }\n          // For rows below the first, delete starting from the target column\n          if (r > 0) {\n            for (let c = colspan - 1; c >= 0; c--) {\n              if (table.rows[i + r] && table.rows[i + r].cells[j]) {\n                table.rows[i + r].deleteCell(j);\n              }\n            }\n          }\n        }\n        // Set rowspan and colspan of the target cell\n        targetCell.rowSpan = rowspan;\n        targetCell.colSpan = colspan;\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: 1, j: 0 }, { i: 2, j: 0 }, { i: 3, j: 0 }, { i: 4, j: 0 }, { i: 5, j: 0 }, { i: 6, j: 0 }, { i: 7, j: 0 }, { i: 8, j: 0 }, { i: 9, j: 0 }, { i: 10, j: 0 }, { i: 11, j: 0 }, { i: 13, j: 0 }, { i: 14, j: 0 },  ], css_id: 'tinytable_css_z43uej0t66jeh1refrc6',}, \n          { positions: [ { i: 1, j: 1 }, { i: 2, j: 1 }, { i: 4, j: 1 }, { i: 5, j: 1 }, { i: 6, j: 1 }, { i: 7, j: 1 }, { i: 8, j: 1 }, { i: 9, j: 1 }, { i: 10, j: 1 }, { i: 11, j: 1 }, { i: 9, j: 2 }, { i: 13, j: 1 }, { i: 14, j: 1 }, { i: 3, j: 2 }, { i: 3, j: 1 }, { i: 1, j: 2 }, { i: 2, j: 2 }, { i: 7, j: 2 }, { i: 4, j: 2 }, { i: 5, j: 2 }, { i: 6, j: 2 }, { i: 11, j: 2 }, { i: 8, j: 2 }, { i: 13, j: 2 }, { i: 10, j: 2 }, { i: 14, j: 2 },  ], css_id: 'tinytable_css_ytbuf0plygvhzzysw9z0',}, \n          { positions: [ { i: 12, j: 2 }, { i: 12, j: 1 },  ], css_id: 'tinytable_css_ro04r08jmmtxibs19y6v',}, \n          { positions: [ { i: 15, j: 0 },  ], css_id: 'tinytable_css_qa6kl0u3f3x17nwkzwen',}, \n          { positions: [ { i: 0, j: 1 }, { i: 0, j: 2 },  ], css_id: 'tinytable_css_linihbawaah4imiuabqj',}, \n          { positions: [ { i: 12, j: 0 },  ], css_id: 'tinytable_css_9huqanmwbj5uzp9624ai',}, \n          { positions: [ { i: 15, j: 1 }, { i: 15, j: 2 },  ], css_id: 'tinytable_css_7fsjl6dv4ltl5j6j30x1',}, \n          { positions: [ { i: 0, j: 0 },  ], css_id: 'tinytable_css_6fzz71m70kygs9j5evn3',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_vkmafstgktf1dfxmi2aw(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_z43uej0t66jeh1refrc6, .table th.tinytable_css_z43uej0t66jeh1refrc6 { text-align: left; }\n      .table td.tinytable_css_ytbuf0plygvhzzysw9z0, .table th.tinytable_css_ytbuf0plygvhzzysw9z0 { text-align: center; }\n      .table td.tinytable_css_ro04r08jmmtxibs19y6v, .table th.tinytable_css_ro04r08jmmtxibs19y6v { text-align: center; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_qa6kl0u3f3x17nwkzwen, .table th.tinytable_css_qa6kl0u3f3x17nwkzwen { text-align: left; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_linihbawaah4imiuabqj, .table th.tinytable_css_linihbawaah4imiuabqj { text-align: center; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_9huqanmwbj5uzp9624ai, .table th.tinytable_css_9huqanmwbj5uzp9624ai { text-align: left; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_7fsjl6dv4ltl5j6j30x1, .table th.tinytable_css_7fsjl6dv4ltl5j6j30x1 { text-align: center; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_6fzz71m70kygs9j5evn3, .table th.tinytable_css_6fzz71m70kygs9j5evn3 { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_vkmafstgktf1dfxmi2aw\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\"> </th>\n                <th scope=\"col\">(1)</th>\n                <th scope=\"col\">(2)</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='3'>+ p < 0.1, * p < 0.05, ** p < 0.01, *** p < 0.001</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td>(Intercept)</td>\n                  <td>0.641**</td>\n                  <td>0.641**</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.195)</td>\n                  <td>(0.230)</td>\n                </tr>\n                <tr>\n                  <td>gini_disp</td>\n                  <td>-0.005</td>\n                  <td>-0.005</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.005)</td>\n                  <td>(0.006)</td>\n                </tr>\n                <tr>\n                  <td>pr_fctPR System</td>\n                  <td>0.083</td>\n                  <td>0.083</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.062)</td>\n                  <td>(0.082)</td>\n                </tr>\n                <tr>\n                  <td>region1Africa</td>\n                  <td>-0.094</td>\n                  <td>-0.094</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.114)</td>\n                  <td>(0.100)</td>\n                </tr>\n                <tr>\n                  <td>region1Europe</td>\n                  <td>0.176**</td>\n                  <td>0.176*</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.067)</td>\n                  <td>(0.079)</td>\n                </tr>\n                <tr>\n                  <td>region1Americas</td>\n                  <td>0.168*</td>\n                  <td>0.168*</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.071)</td>\n                  <td>(0.080)</td>\n                </tr>\n                <tr>\n                  <td>Num.Obs.</td>\n                  <td>77</td>\n                  <td>77</td>\n                </tr>\n                <tr>\n                  <td>R2</td>\n                  <td>0.305</td>\n                  <td>0.305</td>\n                </tr>\n                <tr>\n                  <td>R2 Adj.</td>\n                  <td>0.256</td>\n                  <td>0.256</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\nWat merken we op:\n\n-   De coëfficiënten veranderen niet, enkel de standaardfouten. Dat zagen we ook bij heteroskedasticiteit-robuuste standaardfouten en geclusterde standaardfouten\n-   De standaardfouten zijn verschillend. Doorgaans, maar niet altijd, zijn gebootstrapte standaardfouten groter.\n-   Conclusies over de significantie van resultaten blijven hier dezelfde, hoewel we zien dat het significantieniveau voor de coëfficiënt van `region1Europe` veranderd is van p \\< 0.01 naar p \\< 0.05. De gevolgen kunnen veel groter zijn in andere analyses.\n\nZoals gezegd neemt R zelf nieuwe toevalssteekproeven. Standaard worden 250 steekproeven genomen. Zoals eerder gezegd zet je een 'seed' om resultaten gelijk te houden, maar natuurlijk is het niet echt betrouwbaar als resultaten bij elke trekking sterk veranderen. Vooraleer te beslissen om je seed vast te leggen, wil je nagaan of resultaten sterk verschillen zonder seed. Als dit het geval is, wil je R vragen meer steekproeven te trekken om betere schattingen te maken van de standaardfouten. Dit doen we in onderstaande syntax door R om 1000 steekproeven te vragen. We zetten een seed in de syntax, maar ga ervanuit dat we eerst goed gekeken hebben naar verschillende uitkomsten vooraleer een seed te zetten.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1) \n\nmodelsummary(norm_model, \n             stars = T, \n             vcov = \"bootstrap\", \n             R = 1000, \n             gof_map = c(\"nobs\", \"r.squared\", \"adj.r.squared\"))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_a9n0dmwc3yte59unpwgn(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_a9n0dmwc3yte59unpwgn\");\n          var cell = table.rows[i]?.cells[j];  // Safe navigation to avoid errors\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function insertSpanRow(i, colspan, content) {\n        var table = document.getElementById('tinytable_a9n0dmwc3yte59unpwgn');\n        var newRow = table.insertRow(i);\n        var newCell = newRow.insertCell(0);\n        newCell.setAttribute(\"colspan\", colspan);\n        // newCell.innerText = content;\n        // this may be unsafe, but innerText does not interpret <br>\n        newCell.innerHTML = content;\n      }\n      function spanCell_a9n0dmwc3yte59unpwgn(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_a9n0dmwc3yte59unpwgn\");\n        const targetRow = table.rows[i];\n        const targetCell = targetRow.cells[j];\n        for (let r = 0; r < rowspan; r++) {\n          // Only start deleting cells to the right for the first row (r == 0)\n          if (r === 0) {\n            // Delete cells to the right of the target cell in the first row\n            for (let c = colspan - 1; c > 0; c--) {\n              if (table.rows[i + r].cells[j + c]) {\n                table.rows[i + r].deleteCell(j + c);\n              }\n            }\n          }\n          // For rows below the first, delete starting from the target column\n          if (r > 0) {\n            for (let c = colspan - 1; c >= 0; c--) {\n              if (table.rows[i + r] && table.rows[i + r].cells[j]) {\n                table.rows[i + r].deleteCell(j);\n              }\n            }\n          }\n        }\n        // Set rowspan and colspan of the target cell\n        targetCell.rowSpan = rowspan;\n        targetCell.colSpan = colspan;\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: 12, j: 0 },  ], css_id: 'tinytable_css_qz91p7vsl3vumswgteif',}, \n          { positions: [ { i: 15, j: 1 },  ], css_id: 'tinytable_css_qj0tbkexod4inq3m0qwa',}, \n          { positions: [ { i: 0, j: 0 },  ], css_id: 'tinytable_css_irkednloob3vrq1w5n5w',}, \n          { positions: [ { i: 15, j: 0 },  ], css_id: 'tinytable_css_hcqnq4enoc5m6eicbmep',}, \n          { positions: [ { i: 12, j: 1 },  ], css_id: 'tinytable_css_8juvk4v85u712zoq3t9n',}, \n          { positions: [ { i: 1, j: 1 }, { i: 2, j: 1 }, { i: 3, j: 1 }, { i: 4, j: 1 }, { i: 5, j: 1 }, { i: 6, j: 1 }, { i: 7, j: 1 }, { i: 8, j: 1 }, { i: 9, j: 1 }, { i: 10, j: 1 }, { i: 11, j: 1 }, { i: 13, j: 1 }, { i: 14, j: 1 },  ], css_id: 'tinytable_css_3em4ieutg9b9jh0wn0wd',}, \n          { positions: [ { i: 1, j: 0 }, { i: 2, j: 0 }, { i: 3, j: 0 }, { i: 4, j: 0 }, { i: 5, j: 0 }, { i: 6, j: 0 }, { i: 7, j: 0 }, { i: 8, j: 0 }, { i: 9, j: 0 }, { i: 10, j: 0 }, { i: 11, j: 0 }, { i: 13, j: 0 }, { i: 14, j: 0 },  ], css_id: 'tinytable_css_0x8571ipymezm5t8p41e',}, \n          { positions: [ { i: 0, j: 1 },  ], css_id: 'tinytable_css_0iecoxh5nvlyzyh6fmv6',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_a9n0dmwc3yte59unpwgn(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_qz91p7vsl3vumswgteif, .table th.tinytable_css_qz91p7vsl3vumswgteif { text-align: left; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_qj0tbkexod4inq3m0qwa, .table th.tinytable_css_qj0tbkexod4inq3m0qwa { text-align: center; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_irkednloob3vrq1w5n5w, .table th.tinytable_css_irkednloob3vrq1w5n5w { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_hcqnq4enoc5m6eicbmep, .table th.tinytable_css_hcqnq4enoc5m6eicbmep { text-align: left; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_8juvk4v85u712zoq3t9n, .table th.tinytable_css_8juvk4v85u712zoq3t9n { text-align: center; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_3em4ieutg9b9jh0wn0wd, .table th.tinytable_css_3em4ieutg9b9jh0wn0wd { text-align: center; }\n      .table td.tinytable_css_0x8571ipymezm5t8p41e, .table th.tinytable_css_0x8571ipymezm5t8p41e { text-align: left; }\n      .table td.tinytable_css_0iecoxh5nvlyzyh6fmv6, .table th.tinytable_css_0iecoxh5nvlyzyh6fmv6 { text-align: center; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_a9n0dmwc3yte59unpwgn\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\"> </th>\n                <th scope=\"col\">(1)</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='2'>+ p < 0.1, * p < 0.05, ** p < 0.01, *** p < 0.001</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td>(Intercept)</td>\n                  <td>0.641**</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.216)</td>\n                </tr>\n                <tr>\n                  <td>gini_disp</td>\n                  <td>-0.005</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.006)</td>\n                </tr>\n                <tr>\n                  <td>pr_fctPR System</td>\n                  <td>0.083</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.079)</td>\n                </tr>\n                <tr>\n                  <td>region1Africa</td>\n                  <td>-0.094</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.101)</td>\n                </tr>\n                <tr>\n                  <td>region1Europe</td>\n                  <td>0.176*</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.076)</td>\n                </tr>\n                <tr>\n                  <td>region1Americas</td>\n                  <td>0.168*</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.081)</td>\n                </tr>\n                <tr>\n                  <td>Num.Obs.</td>\n                  <td>77</td>\n                </tr>\n                <tr>\n                  <td>R2</td>\n                  <td>0.305</td>\n                </tr>\n                <tr>\n                  <td>R2 Adj.</td>\n                  <td>0.256</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\n`R = 1000`\n\n:   Deze optie laat toe het aantal steekproeven dat R trekt aan te passen. Hier vragen we er 1000.\n\nOnze resultaten hier zijn gelijkaardig, maar niet identiek aan deze gevonden bij 250 steekproeven. Het heeft echter geen gevolgen voor de algemene conclusies over significantie.\n\nBootstrapping kan ook gebruikt worden binnen het `marginaleffects` package, bv. wanneer we voorspelde waarden en betrouwbaarheidsintervallen nodig hebben. De functie om bootstrapping te gebruiken (`inferences()`) is echter nog steeds in ontwikkeling en je moet er ook bijkomende packages voor installeren. Indien je dit nodig zou hebben, bekijk dan het [\"Bootstrap\"](https://marginaleffects.com/bonus/bootstrap.html) hoofdstuk op de `marginaleffects` website.\n",
    "supporting": [
      "errors_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}